services:
    # Example custom templating helper
    # app.templating.helper.foobar:
    #    class: AppBundle\Templating\Helper\Example
    #    tags:
    #        - { name: templating.helper, alias: fooBar }

    # Example event listener for objects
    # app.event_listener.test:
    #    class: AppBundle\EventListener\TestListener
    #    tags:
    #        - { name: kernel.event_listener, event: pimcore.object.preUpdate, method: onObjectPreUpdate }

    website_demo.area.brick.blockquote:
        class: AppBundle\Document\Areabrick\Blockquote
        tags:
            - { name: pimcore.area.brick, id: blockquote }

    website_demo.language_switcher:
        class: AppBundle\Templating\LanguageSwitcher
        arguments: ['@pimcore.document_service']
